//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiThucHanh02.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class SanPham
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Tên sản phẩm không được để trống.")]
        public string Name { get; set; }
        public string Image { get; set; }

        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public Nullable<double> Discount { get; set; }
        [NotMapped] // Không lưu vào DB
        public HttpPostedFileBase ImageFile { get; set; }
        [NotMapped]
        public double? NewPrice
        {
            get
            {
                if (Discount.HasValue && Discount.Value > 0)
                {
                    return Price - (Price * Discount.Value / 100);
                }
                return null;
            }
        }
    }
}
